server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /lmapi
spring:
  devtools:
    restart:
      enabled: true
      additional-paths:
        - src/java/main
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates
    servlet:
      content-type: text/html
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/manager?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 下面为连接池的补充设置，应用到上面所有数据源中

      initial-size: 20
      min-idle: 5
      max-active: 100
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 100
      # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      aop-patterns:
        - com.vector.manager.sys.service.*
        - com.vector.manager.sys.dao.*
        - com.vector.manager.job.service.*
        - com.vector.manager.job.dao.*
        - com.vector.manager.cms.service.*
        - com.vector.manager.cms.dao.*
      #是否启用StatFilter默认值false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        # 缺省sessionStatMaxCount是1000个
        session-stat-max-count: 1000
        profile-enable: true
        principal-cookie-name: admin
        principal-session-name: admin
      stat-view-servlet:
        allow:
        enabled: true
        login-username: root
        login-password: 123456
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

redis:
  # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
  database: 0
  # redis服务器地址（默认为loaclhost）
  host: 127.0.0.1
  # redis端口（默认为6379）
  port: 6379
  # redis访问密码（默认为空）
  # redis连接超时时间（单位毫秒）
  timeout: 0
  # redis连接池配置
  pool:
    # 最大可用连接数（默认为8，负数表示无限）
    max-active: 8
    # 最大空闲连接数（默认为8，负数表示无限）
    max-idle: -1
    # 最小空闲连接数（默认为0，该值只有为正数才有用）
    min-idle: 8
    # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
    max-wait: 0
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.vector.manager.*.entity
  #支持统配符 * 或者 ; 分割
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
    #开启 SQL 解析缓存注解生效
    sql-parser-cache: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  config: classpath:log4j2.xml
#  level:
#    top.longmarch: debug
